import { type Metadata } from "next";

import { ClerkProvider } from "@clerk/nextjs";
import "~/styles/globals.css";
import { TopNav } from "./_components/topnav";

export const metadata: Metadata = {
  title: "Nextgram",
  description: "Generated by Tharo",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`flex flex-col gap-4 font-sans`}>
          <TopNav />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
